name: myfirst-action
on: workflow_dispatch
jobs:
  myfirstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Print "Greetings"
        run: echo "Hello me, I guess"
      - name: Print "Congratulations"
        run: echo "From Nataliya Maroz"
